name: Company File Upload

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'  # Specify the PHP version you need

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.myautomation1.website
        username: ${{ secrets.TEST_USERNAME }}  # Use GitHub secret for FTP username
        password: ${{ secrets.TEST_PASSWORD }}
        port: 21  # Replace with the correct port number (21 is standard for FTP)
        protocol: ftp

        
    # - name: Directory Permissions
    #   run: |
    #       sudo chown -R $USER:www-data storage bootstrap/cache
    #       sudo chmod -R 775 storage bootstrap/cache

    # - name: Change directory
    #   run: ls
    
    # - name: Make deploy.sh executable
    #   run: chmod +x deploy.sh

    # - name: Execute deploy.sh 
    #   run: ./deploy.sh


   

   
